name: Azure Backend Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore Dependencies
        run: dotnet restore backend/backend.csproj

      - name: Build Project
        run: dotnet build backend/backend.csproj -c Release --no-restore

      - name: Publish Project
        run: dotnet publish backend/backend.csproj -c Release -o ./publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'web-app-api-ghfmdweuf7h7ezen'
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: './publish'
